/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './message-input.component.ngfactory';
import * as import2 from './message-input.component';
import * as import3 from './message.service';
import * as import4 from './message-list.component.ngfactory';
import * as import5 from './message-list.component';
import * as import6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_MessagesComponent,
  data: {}
}
);
export function View_MessagesComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-input',([] as any[]),(null as any),(null as any),(null as any),import1.View_MessageInputComponent_0,import1.RenderType_MessageInputComponent)),
    import0.ɵdid(57344,(null as any),0,import2.MessageInputComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),(null as any),import4.View_MessageListComponent_0,import4.RenderType_MessageListComponent)),
    import0.ɵdid(57344,(null as any),0,import5.MessageListComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    ck(v,4,0);
    ck(v,12,0);
  },(null as any));
}
function View_MessagesComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-messages',([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,RenderType_MessagesComponent)),
    import0.ɵdid(24576,(null as any),0,import6.MessagesComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MessagesComponentNgFactory:import0.ComponentFactory<import6.MessagesComponent> = import0.ɵccf('app-messages',import6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdGFyYXQvRHJvcGJveC9Qcm9qZWN0L2FuZ3VsYXIyLW5vZGVqcy9hc3NldHMvYXBwL21lc3NhZ2UvbWVzc2FnZXMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3RhcmF0L0Ryb3Bib3gvUHJvamVjdC9hbmd1bGFyMi1ub2RlanMvYXNzZXRzL2FwcC9tZXNzYWdlL21lc3NhZ2VzLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL3RhcmF0L0Ryb3Bib3gvUHJvamVjdC9hbmd1bGFyMi1ub2RlanMvYXNzZXRzL2FwcC9tZXNzYWdlL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvdGFyYXQvRHJvcGJveC9Qcm9qZWN0L2FuZ3VsYXIyLW5vZGVqcy9hc3NldHMvYXBwL21lc3NhZ2UvbWVzc2FnZXMuY29tcG9uZW50LnRzLk1lc3NhZ2VzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICA8YXBwLW1lc3NhZ2UtaW5wdXQ+PC9hcHAtbWVzc2FnZS1pbnB1dD5cbiAgPC9kaXY+XG4gIDxocj5cbiAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgIDxhcHAtbWVzc2FnZS1saXN0PjwvYXBwLW1lc3NhZ2UtbGlzdD5cbiAgPC9kaXY+XG4gICIsIjxhcHAtbWVzc2FnZXM+PC9hcHAtbWVzc2FnZXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDRTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWlCO0lBQ2Y7Z0JBQUE7SUFBdUM7SUFDbkM7SUFDTjtJQUFJO01BQ0o7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFpQjtJQUNmO2dCQUFBO0lBQXFDO0lBQ2pDOzs7SUFMSjtJQUlBOzs7OztJQ05KO2dCQUFBOzs7OyJ9
