/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './auth.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from '@angular/router';
import * as import5 from './signup.component.ngfactory';
import * as import6 from './signin.component.ngfactory';
import * as import7 from './logout.component.ngfactory';
import * as import8 from './signup.component';
import * as import9 from './signin.component';
import * as import10 from './logout.component';
class AuthModuleInjector extends import0.ɵNgModuleInjector<import1.AuthModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _ReactiveFormsModule_2:import3.ReactiveFormsModule;
  _RouterModule_3:import4.RouterModule;
  _AuthModule_4:import1.AuthModule;
  __NgLocalization_5:import2.NgLocaleLocalization;
  __FormBuilder_6:import3.FormBuilder;
  __ɵi_7:import3.ɵi;
  _ROUTES_8:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import5.SignupComponentNgFactory,
      import6.SigninComponentNgFactory,
      import7.LogoutComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_5():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _FormBuilder_6():import3.FormBuilder {
    if ((this.__FormBuilder_6 == null)) { (this.__FormBuilder_6 = new import3.FormBuilder()); }
    return this.__FormBuilder_6;
  }
  get _ɵi_7():import3.ɵi {
    if ((this.__ɵi_7 == null)) { (this.__ɵi_7 = new import3.ɵi()); }
    return this.__ɵi_7;
  }
  createInternal():import1.AuthModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._ReactiveFormsModule_2 = new import3.ReactiveFormsModule();
    this._RouterModule_3 = new import4.RouterModule(this.parent.get(import4.ɵa,(null as any)),this.parent.get(import4.Router,(null as any)));
    this._AuthModule_4 = new import1.AuthModule();
      this._ROUTES_8 = [[
        {
          path: '',
          redirectTo: 'signup',
          pathMatch: 'full'
        }
        ,
        {
          path: 'signup',
          component: import8.SignupComponent
        }
        ,
        {
          path: 'signin',
          component: import9.SigninComponent
        }
        ,
        {
          path: 'logout',
          component: import10.LogoutComponent
        }

      ]
    ];
    return this._AuthModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_2; }
    if ((token === import4.RouterModule)) { return this._RouterModule_3; }
    if ((token === import1.AuthModule)) { return this._AuthModule_4; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_6; }
    if ((token === import3.ɵi)) { return this._ɵi_7; }
    if ((token === import4.ROUTES)) { return this._ROUTES_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AuthModuleNgFactory:import0.NgModuleFactory<import1.AuthModule> = new import0.NgModuleFactory<any>(AuthModuleInjector,import1.AuthModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdGFyYXQvRHJvcGJveC9Qcm9qZWN0L2FuZ3VsYXIyLW5vZGVqcy9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvdGFyYXQvRHJvcGJveC9Qcm9qZWN0L2FuZ3VsYXIyLW5vZGVqcy9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
